
create view DBSINGULAR.VW_ATOR AS
SELECT A.CO_ATOR, C.CO_USERNAME as "CO_USUARIO", C.NO_USUARIO  as "NO_ATOR", C.DS_EMAIL
FROM DBSINGULAR.TB_ATOR A RIGHT JOIN DBSEGURANCA.TB_USUARIO C
ON C.CO_USERNAME = A.CO_USUARIO;
drop table DBSINGULAR.RL_PERMISSAO_TAREFA CASCADE CONSTRAINTS ;
create view  DBSINGULAR.RL_PERMISSAO_TAREFA AS
select 1 as "CO_PERMISSAO_TAREFA", t.CO_DEFINICAO_TAREFA from DBSINGULAR.TB_DEFINICAO_TAREFA t where upper(t.SG_TAREFA) like upper('%analise%')
union
select 2 as "CO_PERMISSAO_TAREFA", t.CO_DEFINICAO_TAREFA from DBSINGULAR.TB_DEFINICAO_TAREFA t where upper(t.SG_TAREFA) not like upper('%analise%');