
create view DBSINGULAR.VW_ATOR AS
SELECT A.CO_ATOR, C.CO_USERNAME as "CO_USUARIO", C.NO_USUARIO  as "NO_ATOR", C.DS_EMAIL
FROM DBSINGULAR.TB_ATOR A RIGHT JOIN DBSEGURANCA.TB_USUARIO C
ON C.CO_USERNAME = A.CO_USUARIO;