

CREATE VIEW DBSINGULAR.VW_ATOR as
SELECT A.CO_ATOR, C.CO_USUARIO, C.NO_NOME as "NO_ATOR", C.DS_EMAIL
FROM DBSINGULAR.TB_ATOR A RIGHT JOIN
DBSEGURANCA.TB_USUARIO C
ON C.CO_USUARIO = A.CO_USUARIO;




