-- Script de carga inicial de dados

INSERT INTO DBSINGULAR.TB_TIPO_TAREFA (DS_TIPO_TAREFA) VALUES ('Automática') -- JAVA
INSERT INTO DBSINGULAR.TB_TIPO_TAREFA (DS_TIPO_TAREFA) VALUES ('Tarefa de Usuário') -- HUMANA
INSERT INTO DBSINGULAR.TB_TIPO_TAREFA (DS_TIPO_TAREFA) VALUES ('Espera') -- ESPERA
INSERT INTO DBSINGULAR.TB_TIPO_TAREFA (DS_TIPO_TAREFA) VALUES ('Fim') -- FIM