-- Script de carga inicial de dados

INSERT INTO DBSINGULAR.TB_TIPO_TAREFA (CO_TIPO_TAREFA, DS_TIPO_TAREFA) VALUES (1, 'Automática'); -- JAVA
INSERT INTO DBSINGULAR.TB_TIPO_TAREFA (CO_TIPO_TAREFA, DS_TIPO_TAREFA) VALUES (2, 'Tarefa de Usuário'); -- HUMANA
INSERT INTO DBSINGULAR.TB_TIPO_TAREFA (CO_TIPO_TAREFA, DS_TIPO_TAREFA) VALUES (3, 'Espera'); -- ESPERA
INSERT INTO DBSINGULAR.TB_TIPO_TAREFA (CO_TIPO_TAREFA, DS_TIPO_TAREFA) VALUES (4, 'Fim'); -- FIM


INSERT INTO DBSINGULAR.TB_ATOR (CO_ATOR, NO_ATOR, DS_EMAIL) VALUES (1, 'User_1', 'user1@gmail.com');
INSERT INTO DBSINGULAR.TB_ATOR (CO_ATOR, NO_ATOR, DS_EMAIL) VALUES (2, 'User_2', 'user2@gmail.com');
INSERT INTO DBSINGULAR.TB_ATOR (CO_ATOR, NO_ATOR, DS_EMAIL) VALUES (3, 'User_3', 'user3@gmail.com');
INSERT INTO DBSINGULAR.TB_ATOR (CO_ATOR, NO_ATOR, DS_EMAIL) VALUES (4, 'User_4', 'user4@gmail.com');
