-- Script de carga inicial de dados


INSERT INTO DBSINGULAR.TB_ATOR (CO_USUARIO, CO_ATOR) VALUES ('vinicius.nunes', 1);
INSERT INTO DBSINGULAR.TB_ATOR (CO_USUARIO, CO_ATOR) VALUES ('delfino.filho', 2);
INSERT INTO DBSINGULAR.TB_ATOR (CO_USUARIO, CO_ATOR) VALUES ('lucas.lopes', 3);
INSERT INTO DBSINGULAR.TB_ATOR (CO_USUARIO, CO_ATOR) VALUES ('ronald.tetsuo', 4);
INSERT INTO DBSINGULAR.TB_ATOR (CO_USUARIO, CO_ATOR) VALUES ('alfredo.fialho', 5);
INSERT INTO DBSINGULAR.TB_ATOR (CO_USUARIO, CO_ATOR) VALUES ('fabricio.buzeto', 6);
INSERT INTO DBSINGULAR.TB_ATOR (CO_USUARIO, CO_ATOR) VALUES ('danilo.custodio', 7);
INSERT INTO DBSINGULAR.TB_ATOR (CO_USUARIO, CO_ATOR) VALUES ('daniel', 8);
INSERT INTO DBSINGULAR.TB_ATOR (CO_USUARIO, CO_ATOR) VALUES ('andre.terra', 9);



INSERT INTO DBSINGULAR.TB_GRUPO_PROCESSO
VALUES
(
'SINGULARTEST',
'Singular Test',
'url'
);