---------------------
-- PESSOA_JURIDICA
---------------------
INSERT INTO DBFORM.TB_PESSOA_JURIDICA (ID_PESSOA_JURIDICA, NU_CNPJ) VALUES(15, '28177688000107');

---------------------
-- ENDERECO
---------------------
INSERT INTO DBFORM.TB_ENDERECO (CO_SEQ_ENDERECO, NO_CEP) VALUES (1, '72260856');

------------------
-- POSTO_ATENDIMENTO
------------------
INSERT INTO DBFORM.TB_POSTO_ATENDIMENTO (CO_SEQ_POSTO_ATENDIMENTO, CO_SEQ_ENDERECO, DS_EMAIL) VALUES (1, 1, 'cov@anvisa.gov.br');

------------------
-- POSTO_EXTERNO
------------------
INSERT INTO DBFORM.TB_POSTO_EXTERNO (CO_POSTO_ATENDIMENTO, ID_PESSOA_JURIDICA) VALUES (1, 15);

