

CREATE TABLE DBSINGULAR.TB_USUARIO_CLIENTE_TESTE (
   CO_USUARIO  VARCHAR(60)       NOT NULL,
   NO_NOME VARCHAR(200),
   DS_EMAIL VARCHAR(200),
  CONSTRAINT PK_USUARIO_CLIENTE_TESTE PRIMARY KEY (CO_USUARIO)
);


CREATE VIEW DBSINGULAR.VW_ATOR as
SELECT A.CO_ATOR, C.CO_USUARIO, C.NO_NOME as "NO_ATOR", C.DS_EMAIL
FROM DBSINGULAR.TB_ATOR A RIGHT JOIN
DBSINGULAR.TB_USUARIO_CLIENTE_TESTE C
ON C.CO_USUARIO = A.CO_USUARIO;




