-- Como ajustar o script gerado pelo PowerDesigner:

-- Remover todos WITH FILLFACTOR= 95
-- Remover todos ON "PRIMARY"
-- Remover todos GO
-- Remover todos os COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS 
-- Substituir VARCHAR(MAX) por VARCHAR(8000)
-- Incluir virgula depois de todos NULL fim de linha
-- Remover constraint primary key das tabelas com IDENTITY
-- inverter ordem do default
-- Colocar index no fim
-- Colocar script de insert no fim
-- Executar em comandos separados o DROP, depois os creates de tabela e schema, depois incluir FKs, depois os inserts


DROP SCHEMA DBSINGULAR IF EXISTS CASCADE;
CREATE SCHEMA DBSINGULAR;
/*==============================================================*/
/* Table: RL_PERMISSAO_PROCESSO                                 */
/*==============================================================*/
CREATE TABLE DBSINGULAR.RL_PERMISSAO_PROCESSO (
   CO_DEFINICAO_PROCESSO BIGINT               NOT NULL,
   TP_PERMISSAO         CHAR(1)              NOT NULL,
      CONSTRAINT CKC_TP_PERMISSAO_RL_PERMI CHECK (TP_PERMISSAO IN ('A','I','C','R')),
   CONSTRAINT PK_PERFIL_PROCESSO PRIMARY KEY (CO_DEFINICAO_PROCESSO, TP_PERMISSAO)
         
   
)



/*==============================================================*/
/* Table: RL_PERMISSAO_TAREFA                                   */
/*==============================================================*/
CREATE TABLE DBSINGULAR.RL_PERMISSAO_TAREFA (
   CO_TAREFA            BIGINT               NOT NULL,
   CO_DEFINICAO_TAREFA  BIGINT               NULL,
   CONSTRAINT PK_PERMISSAO_TAREFA PRIMARY KEY (CO_TAREFA)
         
   
)



/*==============================================================*/
/* Table: TB_ATOR                                               */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_ATOR (
   CO_ATOR              BIGINT               NOT NULL,
   CONSTRAINT PK_ATOR PRIMARY KEY (CO_ATOR)
         
   
)



/*==============================================================*/
/* Table: TB_CATEGORIA                                          */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_CATEGORIA (
   CO_CATEGORIA         BIGINT               IDENTITY,
   NO_CATEGORIA         VARCHAR(100)          NOT NULL,
   
         
   
   CONSTRAINT AK_AK_CATEGORIA_TB_CATEG UNIQUE (NO_CATEGORIA)
)



/*==============================================================*/
/* Table: TB_DEFINICAO_PROCESSO                                 */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_DEFINICAO_PROCESSO (
   CO_DEFINICAO_PROCESSO BIGINT               IDENTITY,
   SG_PROCESSO          VARCHAR(200)          NOT NULL,
   NO_PROCESSO          VARCHAR(200)          NOT NULL,
   NO_CLASSE_JAVA       VARCHAR(500)          NOT NULL,
   CO_CATEGORA          BIGINT               NULL,
   
   CONSTRAINT AK_AK_DEFINICAO_PROCE_TB_DEFIN UNIQUE (SG_PROCESSO)
)


/*==============================================================*/
/* Table: TB_DEFINICAO_TAREFA                                   */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_DEFINICAO_TAREFA (
   CO_DEFINICAO_TAREFA  BIGINT               IDENTITY,
   CO_DEFINICAO_PROCESSO BIGINT               NOT NULL,
   SG_TAREFA            VARCHAR(100)         NOT NULL,
   
   CONSTRAINT AK_AK_DEFINICAO_TAREF_TB_DEFIN UNIQUE (CO_DEFINICAO_PROCESSO, SG_TAREFA)
)


/*==============================================================*/
/* Table: TB_HISTORICO_INSTANCIA_TAREFA                         */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_HISTORICO_INSTANCIA_TAREFA (
   CO_HISTORICO_ALOCACAO BIGINT               IDENTITY,
   CO_INSTANCIA_TAREFA  BIGINT               NOT NULL,
   DT_INICIO_ALOCACAO   DATETIME             NOT NULL,
   CO_TIPO_HISTORICO_TAREFA BIGINT               NOT NULL,
   DT_FIM_ALOCACAO      DATETIME             NULL,
   CO_ATOR_ALOCADO      BIGINT               NULL,
   CO_ATOR_ALOCADOR     BIGINT               NULL,
   DS_COMPLEMENTO       VARCHAR(8000)          NULL
   
         
   
)




/*==============================================================*/
/* Table: TB_INSTANCIA_PAPEL                                    */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_INSTANCIA_PAPEL (
   CO_INSTANCIA_PAPEL   BIGINT               IDENTITY,
   CO_INSTANCIA_PROCESSO BIGINT               NOT NULL,
   CO_PAPEL             BIGINT               NOT NULL,
   CO_ATOR              BIGINT               NOT NULL,
   DT_CRIACAO           DATETIME             NOT NULL,
   CO_ATOR_ALOCADOR     BIGINT               NULL,
   
         
   
   CONSTRAINT AK_AK_INSTANCIA_PAPEL_TB_INSTA UNIQUE (CO_INSTANCIA_PROCESSO, CO_PAPEL)
)



/*==============================================================*/
/* Table: TB_INSTANCIA_PROCESSO                                 */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_INSTANCIA_PROCESSO (
   CO_INSTANCIA_PROCESSO BIGINT               IDENTITY,
   CO_PROCESSO          BIGINT               NOT NULL,
   DT_INICIO            DATETIME             NOT NULL,
   DT_FIM               DATETIME             NULL,
   DS_INSTANCIA_PROCESSO VARCHAR(300)          NULL,
   CO_ATOR_CRIADOR      BIGINT               NULL,
   CO_INSTANCIA_TAREFA_PAI BIGINT               NULL,
   CO_TAREFA_ATUAL      BIGINT               NULL
   
         
   
)





/*==============================================================*/
/* Table: TB_INSTANCIA_TAREFA                                   */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_INSTANCIA_TAREFA (
   CO_INSTANCIA_TAREFA  BIGINT               IDENTITY,
   CO_INSTANCIA_PROCESSO BIGINT               NOT NULL,
   CO_TAREFA            BIGINT               NOT NULL,
   DT_INICIO            DATETIME             NOT NULL,
   DT_FIM               DATETIME             NULL,
   DT_ESPERADA_FIM      DATETIME             NULL,
   CO_ATOR_ALOCADO      BIGINT               NULL,
   CO_ATOR_CONCLUSAO    BIGINT               NULL,
   CO_TRANSICAO_EXECUTADA BIGINT               NULL,
   DATA_ALVO_SUSPENSAO  DATETIME             NULL,
   SE_SUSPENSA          BIT                  NULL,
   DATA_ALVO_FIM        DATETIME             NULL
         
   
)





/*==============================================================*/
/* Table: TB_PAPEL                                              */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_PAPEL (
   CO_PAPEL             BIGINT               IDENTITY,
   CO_DEFINICAO_PROCESSO BIGINT               NULL,
   SG_PAPEL             VARCHAR(100)          NOT NULL,
   NO_PAPEL             VARCHAR(300)          NOT NULL,
         
   
   CONSTRAINT AK_AK_PAPEL_TB_PAPEL UNIQUE (CO_DEFINICAO_PROCESSO, SG_PAPEL)
)



/*==============================================================*/
/* Table: TB_PROCESSO                                           */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_PROCESSO (
   CO_PROCESSO          BIGINT               IDENTITY,
   CO_DEFINICAO_PROCESSO BIGINT               NOT NULL,
   DT_VERSAO            DATETIME             NOT NULL
         
   
)




/*==============================================================*/
/* Table: TB_TAREFA                                             */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_TAREFA (
   CO_TAREFA            BIGINT               IDENTITY,
   CO_PROCESSO          BIGINT               NOT NULL,
   CO_DEFINICAO_TAREFA  BIGINT               NOT NULL,
   NO_TAREFA            VARCHAR(300)          NOT NULL,
   CO_TIPO_TAREFA       BIGINT               NOT NULL,
         
   
   CONSTRAINT AK_AK_TAREFA_TB_TAREF UNIQUE (CO_PROCESSO, CO_DEFINICAO_TAREFA),
   CONSTRAINT AK_AK_TAREFA_NOME_TB_TAREF UNIQUE (CO_PROCESSO, NO_TAREFA)
)



/*==============================================================*/
/* Table: TB_TIPO_HISTORICO_TAREFA                              */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_TIPO_HISTORICO_TAREFA (
   CO_TIPO_HISTORICO_TAREFA BIGINT               IDENTITY,
   DS_TIPO_HISTORICO_TAREFA VARCHAR(100)          NOT NULL,
   CONSTRAINT AK_AK_TIPO_HISTORICO__TB_TIPO_ UNIQUE (DS_TIPO_HISTORICO_TAREFA)
)



/*==============================================================*/
/* Table: TB_TIPO_TAREFA                                        */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_TIPO_TAREFA (
   CO_TIPO_TAREFA       BIGINT               IDENTITY,
   DS_TIPO_TAREFA       VARCHAR(100)          NOT NULL,
   CONSTRAINT AK_AK_TIPO_TAREFA_TB_TIPO_ UNIQUE (DS_TIPO_TAREFA)
)



/*==============================================================*/
/* Table: TB_TIPO_VARIAVEL                                      */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_TIPO_VARIAVEL (
   CO_TIPO_VARIAVEL     BIGINT               IDENTITY,
   NO_CLASSE_JAVA       VARCHAR(300)          NOT NULL,
   DS_TIPO_VARIAVEL     VARCHAR(100)         NOT NULL,
   CONSTRAINT AK_AK_TIPO_VARIAVEL_TB_TIPO_ UNIQUE (NO_CLASSE_JAVA)
)



/*==============================================================*/
/* Table: TB_TRANSICAO                                          */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_TRANSICAO (
   CO_TRANSICAO         BIGINT               IDENTITY,
   CO_TAREFA_ORIGEM     BIGINT               NOT NULL,
   CO_TAREFA_DESTINO    BIGINT               NOT NULL,
   NO_TRANSICAO         VARCHAR(300)         NOT NULL,
   SG_TRANSICAO         VARCHAR(100)         NOT NULL,
   TP_TRANSICAO         CHAR(1)              DEFAULT 'E' NOT NULL,
      CONSTRAINT CKC_TP_TRANSICAO_TB_TRANS CHECK (TP_TRANSICAO IN ('E','A','H')),
   CONSTRAINT AK_AK_TRANSICAO_TB_TRANS UNIQUE (CO_TAREFA_ORIGEM, SG_TRANSICAO)
)


/*==============================================================*/
/* Table: TB_VARIAVEL                                           */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_VARIAVEL (
   CO_VARIAVEL          BIGINT               IDENTITY,
   CO_INSTANCIA_PROCESSO BIGINT               NOT NULL,
   NO_VARIAVEL          VARCHAR(100)          NOT NULL,
   CO_TIPO_VARIAVEL     BIGINT               NOT NULL,
   VL_VARIAVEL          VARCHAR(8000)          NULL,
   CONSTRAINT AK_AK_VARIAVEL_TB_VARIA UNIQUE (CO_INSTANCIA_PROCESSO, NO_VARIAVEL)
)



/*==============================================================*/
/* Table: TB_VARIAVEL_EXECUCAO_TRANSICAO                        */
/*==============================================================*/
CREATE TABLE DBSINGULAR.TB_VARIAVEL_EXECUCAO_TRANSICAO (
   CO_VARIAVEL_EXECUCAO_TRANSICAO BIGINT               IDENTITY,
   CO_INSTANCIA_TAREFA_ORIGEM BIGINT               NOT NULL,
   NO_VARIAVEL          VARCHAR(100)         NOT NULL,
   CO_INSTANCIA_TAREFA_DESTINO BIGINT               NOT NULL,
   CO_INSTANCIA_PROCESSO BIGINT               NOT NULL,
   CO_VARIAVEL_INSTANCIA_PROCESSO BIGINT               NULL,
   VL_NOVO              VARCHAR(8000)          NULL,
   DT_HISTORICO         DATETIME             NOT NULL,
   CO_TIPO_VARIAVEL     BIGINT               NOT NULL,
   CONSTRAINT AK_AK_VARIAVEL_EXECUC_TB_VARIA UNIQUE (CO_INSTANCIA_TAREFA_ORIGEM, NO_VARIAVEL)
)



ALTER TABLE DBSINGULAR.RL_PERMISSAO_PROCESSO
   ADD CONSTRAINT FK_PERMISSAO_PROCESSO_DEFINICAO_PROCESSO FOREIGN KEY (CO_DEFINICAO_PROCESSO)
      REFERENCES DBSINGULAR.TB_DEFINICAO_PROCESSO (CO_DEFINICAO_PROCESSO)


ALTER TABLE DBSINGULAR.RL_PERMISSAO_TAREFA
   ADD CONSTRAINT FK_PERMISSAO_TAREFA_DEFINICAO_TAREFA FOREIGN KEY (CO_DEFINICAO_TAREFA)
      REFERENCES DBSINGULAR.TB_DEFINICAO_TAREFA (CO_DEFINICAO_TAREFA)


ALTER TABLE DBSINGULAR.TB_DEFINICAO_PROCESSO
   ADD CONSTRAINT FK_DEFINICAO_PROCESSO_CATEGORIA FOREIGN KEY (CO_CATEGORA)
      REFERENCES DBSINGULAR.TB_CATEGORIA (CO_CATEGORIA)


ALTER TABLE DBSINGULAR.TB_DEFINICAO_TAREFA
   ADD CONSTRAINT FK_TB_DEFIN_FK_DEFINI_TB_DEFIN FOREIGN KEY (CO_DEFINICAO_PROCESSO)
      REFERENCES DBSINGULAR.TB_DEFINICAO_PROCESSO (CO_DEFINICAO_PROCESSO)


ALTER TABLE DBSINGULAR.TB_HISTORICO_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_HISTORICO_ALOCACAO_TAREFA_CAD_PESSOA1 FOREIGN KEY (CO_ATOR_ALOCADO)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR)


ALTER TABLE DBSINGULAR.TB_HISTORICO_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_HISTORICO_ALOCACAO_TAREFA_CAD_PESSOA2 FOREIGN KEY (CO_ATOR_ALOCADOR)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR)


ALTER TABLE DBSINGULAR.TB_HISTORICO_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_HISTORICO_ALOCACAO_TAREFA_DMD_TAREFA FOREIGN KEY (CO_INSTANCIA_TAREFA)
      REFERENCES DBSINGULAR.TB_INSTANCIA_TAREFA (CO_INSTANCIA_TAREFA)
         ON DELETE CASCADE


ALTER TABLE DBSINGULAR.TB_HISTORICO_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_HISTORICO_ALOCACAO_TAREFA_DMD_TIPO_HISTORICO_TAREFA FOREIGN KEY (CO_TIPO_HISTORICO_TAREFA)
      REFERENCES DBSINGULAR.TB_TIPO_HISTORICO_TAREFA (CO_TIPO_HISTORICO_TAREFA)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PAPEL
   ADD CONSTRAINT FK_DMD_PAPEL_DEMANDA_CAD_PESSOA FOREIGN KEY (CO_ATOR)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PAPEL
   ADD CONSTRAINT FK_DMD_PAPEL_DEMANDA_CAD_PESSOA1 FOREIGN KEY (CO_ATOR_ALOCADOR)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PAPEL
   ADD CONSTRAINT FK_DMD_PAPEL_DEMANDA_DMD_DEMANDA FOREIGN KEY (CO_INSTANCIA_PROCESSO)
      REFERENCES DBSINGULAR.TB_INSTANCIA_PROCESSO (CO_INSTANCIA_PROCESSO)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PAPEL
   ADD CONSTRAINT FK_DMD_PAPEL_DEMANDA_DMD_PAPEL FOREIGN KEY (CO_PAPEL)
      REFERENCES DBSINGULAR.TB_PAPEL (CO_PAPEL)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PROCESSO
   ADD CONSTRAINT FK_INSTANCIA_PROCESSO_ATOR_CRIADOR FOREIGN KEY (CO_ATOR_CRIADOR)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PROCESSO
   ADD CONSTRAINT FK_DMD_DEMANDA_DMD_TAREFA FOREIGN KEY (CO_INSTANCIA_TAREFA_PAI)
      REFERENCES DBSINGULAR.TB_INSTANCIA_TAREFA (CO_INSTANCIA_TAREFA)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PROCESSO
   ADD CONSTRAINT FK_DMD_DEMANDA_DMD_DEFINICAO FOREIGN KEY (CO_PROCESSO)
      REFERENCES DBSINGULAR.TB_PROCESSO (CO_PROCESSO)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PROCESSO
   ADD CONSTRAINT FK_TB_INSTA_REFERENCE_TB_TAREF FOREIGN KEY (CO_TAREFA_ATUAL)
      REFERENCES DBSINGULAR.TB_TAREFA (CO_TAREFA)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_TAREFA_CAD_PESSOA1 FOREIGN KEY (CO_ATOR_ALOCADO)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_TAREFA_CAD_PESSOA2 FOREIGN KEY (CO_ATOR_CONCLUSAO)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_TAREFA_DMD_DEMANDA1 FOREIGN KEY (CO_INSTANCIA_PROCESSO)
      REFERENCES DBSINGULAR.TB_INSTANCIA_PROCESSO (CO_INSTANCIA_PROCESSO)
         ON DELETE CASCADE


ALTER TABLE DBSINGULAR.TB_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_TAREFA_DMD_SITUACAO FOREIGN KEY (CO_TAREFA)
      REFERENCES DBSINGULAR.TB_TAREFA (CO_TAREFA)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_TB_INSTA_FK_INSTAN_TB_TRANS FOREIGN KEY (CO_TRANSICAO_EXECUTADA)
      REFERENCES DBSINGULAR.TB_TRANSICAO (CO_TRANSICAO)


ALTER TABLE DBSINGULAR.TB_PAPEL
   ADD CONSTRAINT FK_PAPEL_DEFINICAO_PROCESSO FOREIGN KEY (CO_DEFINICAO_PROCESSO)
      REFERENCES DBSINGULAR.TB_DEFINICAO_PROCESSO (CO_DEFINICAO_PROCESSO)


ALTER TABLE DBSINGULAR.TB_PROCESSO
   ADD CONSTRAINT FK_TB_PROCE_FK_PROCES_TB_DEFIN FOREIGN KEY (CO_DEFINICAO_PROCESSO)
      REFERENCES DBSINGULAR.TB_DEFINICAO_PROCESSO (CO_DEFINICAO_PROCESSO)


ALTER TABLE DBSINGULAR.TB_TAREFA
   ADD CONSTRAINT FK_TB_TAREF_FK_TAREFA_TB_DEFIN FOREIGN KEY (CO_DEFINICAO_TAREFA)
      REFERENCES DBSINGULAR.TB_DEFINICAO_TAREFA (CO_DEFINICAO_TAREFA)


ALTER TABLE DBSINGULAR.TB_TAREFA
   ADD CONSTRAINT FK_DMD_SITUACAO_DMD_DEFINICAO FOREIGN KEY (CO_PROCESSO)
      REFERENCES DBSINGULAR.TB_PROCESSO (CO_PROCESSO)
         ON DELETE CASCADE


ALTER TABLE DBSINGULAR.TB_TAREFA
   ADD CONSTRAINT FK_DMD_SITUACAO_DMD_TIPO_SITUACAO FOREIGN KEY (CO_TIPO_TAREFA)
      REFERENCES DBSINGULAR.TB_TIPO_TAREFA (CO_TIPO_TAREFA)


ALTER TABLE DBSINGULAR.TB_TRANSICAO
   ADD CONSTRAINT FK_TRANSICAO_TAREFA_DESTINO FOREIGN KEY (CO_TAREFA_DESTINO)
      REFERENCES DBSINGULAR.TB_TAREFA (CO_TAREFA)


ALTER TABLE DBSINGULAR.TB_TRANSICAO
   ADD CONSTRAINT FK_TRANSICAO_TAREFA_ORIGEM FOREIGN KEY (CO_TAREFA_ORIGEM)
      REFERENCES DBSINGULAR.TB_TAREFA (CO_TAREFA)


ALTER TABLE DBSINGULAR.TB_VARIAVEL
   ADD CONSTRAINT FK_DMD_VARIAVEL_DMD_DEMANDA FOREIGN KEY (CO_INSTANCIA_PROCESSO)
      REFERENCES DBSINGULAR.TB_INSTANCIA_PROCESSO (CO_INSTANCIA_PROCESSO)
         ON DELETE CASCADE


ALTER TABLE DBSINGULAR.TB_VARIAVEL
   ADD CONSTRAINT FK_DMD_VARIAVEL_DMD_TIPO_VARIAVEL FOREIGN KEY (CO_TIPO_VARIAVEL)
      REFERENCES DBSINGULAR.TB_TIPO_VARIAVEL (CO_TIPO_VARIAVEL)


ALTER TABLE DBSINGULAR.TB_VARIAVEL_EXECUCAO_TRANSICAO
   ADD CONSTRAINT FK_DMD_HISTORICO_VARIAVEL_DMD_DEMANDA FOREIGN KEY (CO_INSTANCIA_PROCESSO)
      REFERENCES DBSINGULAR.TB_INSTANCIA_PROCESSO (CO_INSTANCIA_PROCESSO)


ALTER TABLE DBSINGULAR.TB_VARIAVEL_EXECUCAO_TRANSICAO
   ADD CONSTRAINT FK_TB_VARIA_FK_HISTOR_TB_TIPO_ FOREIGN KEY (CO_TIPO_VARIAVEL)
      REFERENCES DBSINGULAR.TB_TIPO_VARIAVEL (CO_TIPO_VARIAVEL)


ALTER TABLE DBSINGULAR.TB_VARIAVEL_EXECUCAO_TRANSICAO
   ADD CONSTRAINT FK_TB_VARIA_FK_HISTOR_TB_VARIA FOREIGN KEY (CO_VARIAVEL_INSTANCIA_PROCESSO)
      REFERENCES DBSINGULAR.TB_VARIAVEL (CO_VARIAVEL)


ALTER TABLE DBSINGULAR.TB_VARIAVEL_EXECUCAO_TRANSICAO
   ADD CONSTRAINT PK_HISTORICO_VARIAVEL_INSTANCIA_TAREFA_DESTINO FOREIGN KEY (CO_INSTANCIA_TAREFA_DESTINO)
      REFERENCES DBSINGULAR.TB_INSTANCIA_TAREFA (CO_INSTANCIA_TAREFA)


ALTER TABLE DBSINGULAR.TB_VARIAVEL_EXECUCAO_TRANSICAO
   ADD CONSTRAINT PK_HISTORICO_VARIAVEL_INSTANCIA_TAREFA_ORIGEM FOREIGN KEY (CO_INSTANCIA_TAREFA_ORIGEM)
      REFERENCES DBSINGULAR.TB_INSTANCIA_TAREFA (CO_INSTANCIA_TAREFA)

/*==============================================================*/
/* Index: IX_INSTANCIA_PROCESSO                                 */
/*==============================================================*/
CREATE INDEX IX_INSTANCIA_PROCESSO ON DBSINGULAR.TB_INSTANCIA_PROCESSO (
CO_PROCESSO ASC,
DT_INICIO ASC
)

	  
/*==============================================================*/
/* Index: IX_HISTORICO_INSTANCIA_TAREFA                         */
/*==============================================================*/
CREATE INDEX IX_HISTORICO_INSTANCIA_TAREFA ON DBSINGULAR.TB_HISTORICO_INSTANCIA_TAREFA (
CO_INSTANCIA_TAREFA ASC,
DT_INICIO_ALOCACAO ASC
)


/*==============================================================*/
/* Index: IX_INSTANCIA_TAREFA                                   */
/*==============================================================*/
CREATE INDEX IX_INSTANCIA_TAREFA ON DBSINGULAR.TB_INSTANCIA_TAREFA (
CO_INSTANCIA_PROCESSO ASC,
DT_INICIO ASC
)

/*==============================================================*/
/* Index: IX_PROCESSO                                           */
/*==============================================================*/
CREATE INDEX IX_PROCESSO ON DBSINGULAR.TB_PROCESSO (
CO_DEFINICAO_PROCESSO ASC,
DT_VERSAO ASC
)


INSERT INTO DBSINGULAR.TB_TIPO_TAREFA (DS_TIPO_TAREFA) VALUES ('Autom�tica') -- JAVA
INSERT INTO DBSINGULAR.TB_TIPO_TAREFA (DS_TIPO_TAREFA) VALUES ('Tarefa de Usu�rio') -- HUMANA
INSERT INTO DBSINGULAR.TB_TIPO_TAREFA (DS_TIPO_TAREFA) VALUES ('Espera') -- ESPERA
INSERT INTO DBSINGULAR.TB_TIPO_TAREFA (DS_TIPO_TAREFA) VALUES ('Fim') -- FIM