/*
 * Copyright (C) 2016 Singular Studios (a.k.a Atom Tecnologia) - www.opensingular.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opensingular.form.exemplos.notificacaosimplificada.domain;

// Generated 16/03/2010 08:00:26

import org.opensingular.lib.support.persistence.enums.SimNao;
import org.opensingular.form.exemplos.notificacaosimplificada.domain.generic.VocabularioControlado;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * EmbalagemPrimariaBasica generated by Vinicius Uriel
 */

@XmlRootElement(name = "embalagem-primaria", namespace = "http://www.anvisa.gov.br/reg-med/schema/domains")
@XmlType(name = "embalagem-primaria", namespace = "http://www.anvisa.gov.br/reg-med/schema/domains")
@Entity
@Table(name = "TB_EMBALAGEM_PRIMARIA", schema = "DBMEDICAMENTO")
@PrimaryKeyJoinColumn(name = "CO_EMBALAGEM_PRIMARIA", referencedColumnName = "CO_SEQ_VOCABULARIO_CONTROLADO")
@NamedQueries({@NamedQuery(name = "EmbalagemPrimariaBasica.findAll", query = "Select embalagemPrimaria From EmbalagemPrimariaBasica as embalagemPrimaria where embalagemPrimaria.ativa = 'S'  Order by embalagemPrimaria.descricao  ")})
public class EmbalagemPrimariaBasica extends VocabularioControlado {

    private static final long serialVersionUID = 4438185164918181904L;

    @Column(name = "SG_EMBALAGEM", nullable = false, length = 10)
    private String sigla;

    public EmbalagemPrimariaBasica() {
    }

    public EmbalagemPrimariaBasica(Long id, String descricao, String sigla, SimNao ativa) {
        this.id = id;
        this.descricao = descricao;
        this.sigla = sigla;
        this.ativa = ativa;
    }

    public String getSigla() {
        return sigla;
    }

    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

}
