/*
 * Copyright (C) 2016 Singular Studios (a.k.a Atom Tecnologia) - www.opensingular.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opensingular.form.exemplos.notificacaosimplificada.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;

import org.opensingular.form.exemplos.notificacaosimplificada.domain.generic.VocabularioControlado;
import org.opensingular.lib.support.persistence.enums.SimNao;
import org.opensingular.lib.support.persistence.util.GenericEnumUserType;

/**
 * LinhaCbpf generated by Vinicius Uriel
 */

@Entity
@Table(name = "TB_LINHA_CBPF", schema = "DBMEDICAMENTO")
@PrimaryKeyJoinColumn(name = "CO_LINHA_CBPF", referencedColumnName = "CO_SEQ_VOCABULARIO_CONTROLADO")
public class LinhaCbpf extends VocabularioControlado {

    private static final long serialVersionUID = -3105005456489332341L;

    @Column(name = "ST_LINHA_RESTRITIVA", nullable = false, length = 1)
    @Type(type = GenericEnumUserType.CLASS_NAME, parameters = {
            @Parameter(name = "enumClass", value = SimNao.ENUM_CLASS_NAME),
            @Parameter(name = "identifierMethod", value = "getCodigo"),
            @Parameter(name = "valueOfMethod", value = "valueOfEnum")})
    private SimNao situacaoLinhaRestritiva;

    public LinhaCbpf() {
    }

    public LinhaCbpf(Long id, String descricao, SimNao ativa) {
        this.id = id;
        this.descricao = descricao;
        this.ativa = ativa;
    }

    public SimNao getSituacaoLinhaRestritiva() {
        return situacaoLinhaRestritiva;
    }

    public void setSituacaoLinhaRestritiva(SimNao situacaoLinhaRestritiva) {
        this.situacaoLinhaRestritiva = situacaoLinhaRestritiva;
    }

}
