ALTER TABLE DBSINGULAR.TB_FORMULARIO
   ADD CONSTRAINT FK_FORMULARIO_COLECAO FOREIGN KEY (CO_COLECAO)
      REFERENCES DBSINGULAR.TB_COLECAO (CO_COLECAO);

ALTER TABLE DBSINGULAR.TB_FORMULARIO
   ADD CONSTRAINT FK_FORMULARIO_TIPO_FORMULARIO FOREIGN KEY (CO_TIPO_FORMULARIO)
      REFERENCES DBSINGULAR.TB_TIPO_FORMULARIO (CO_TIPO_FORMULARIO);

ALTER TABLE DBSINGULAR.TB_COLECAO
   ADD CONSTRAINT FK_COLECAO_TIPO_FORMULARIO FOREIGN KEY (CO_TIPO_FORMULARIO)
      REFERENCES DBSINGULAR.TB_TIPO_FORMULARIO (CO_TIPO_FORMULARIO);

CREATE UNIQUE INDEX IX_TIPO_FORMULARIO ON DBSINGULAR.TB_TIPO_FORMULARIO (
  SG_TIPO_FORMULARIO ASC
);