ALTER TABLE DBSINGULAR.TB_COLECAO
   ADD CONSTRAINT FK_COLECAO_TIPO_FORMULARIO FOREIGN KEY (CO_TIPO_FORMULARIO)
      REFERENCES DBSINGULAR.TB_TIPO_FORMULARIO (CO_TIPO_FORMULARIO);

ALTER TABLE DBSINGULAR.TB_ARQUIVO
   ADD CONSTRAINT FK_TB_ARQUI_FK_ARQUIV_TB_CONTE FOREIGN KEY (CO_CONTEUDO_ARQUIVO)
      REFERENCES DBSINGULAR.TB_CONTEUDO_ARQUIVO (CO_CONTEUDO_ARQUIVO);

ALTER TABLE DBSINGULAR.TB_FORMULARIO
   ADD CONSTRAINT FK_FORMULARIO_COLECAO FOREIGN KEY (CO_COLECAO)
      REFERENCES DBSINGULAR.TB_COLECAO (CO_COLECAO);

ALTER TABLE DBSINGULAR.TB_FORMULARIO
   ADD CONSTRAINT FK_FORMULARIO_TIPO_FORMULARIO FOREIGN KEY (CO_TIPO_FORMULARIO)
      REFERENCES DBSINGULAR.TB_TIPO_FORMULARIO (CO_TIPO_FORMULARIO);

ALTER TABLE DBSINGULAR.TB_FORMULARIO
   ADD CONSTRAINT FK_TB_FORMU_FK_FORM_V_TB_VERSA FOREIGN KEY (CO_VERSAO_ATUAL)
      REFERENCES DBSINGULAR.TB_VERSAO_FORMULARIO (CO_VERSAO_FORMULARIO);

ALTER TABLE DBSINGULAR.TB_VERSAO_ANOTACAO_FORMULARIO
   ADD CONSTRAINT FK_VERANOTFORM_ANOTFORM FOREIGN KEY (CO_VERSAO_FORMULARIO, CO_CHAVE_ANOTACAO)
      REFERENCES DBSINGULAR.TB_ANOTACAO_FORMULARIO (CO_VERSAO_FORMULARIO, CO_CHAVE_ANOTACAO);

ALTER TABLE DBSINGULAR.TB_VERSAO_ANOTACAO_FORMULARIO
   ADD CONSTRAINT FK_TB_VERSA_FK_VER_AN_TB_ATOR FOREIGN KEY (CO_AUTOR_INCLUSAO)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR);

ALTER TABLE DBSINGULAR.TB_VERSAO_FORMULARIO
   ADD CONSTRAINT FK_VERFORM_FORMULARIO FOREIGN KEY (CO_FORMULARIO)
      REFERENCES DBSINGULAR.TB_FORMULARIO (CO_FORMULARIO);

ALTER TABLE DBSINGULAR.TB_VERSAO_FORMULARIO
   ADD CONSTRAINT FK_TB_VERSA_FK_VER_FO_TB_ATOR FOREIGN KEY (CO_AUTOR_INCLUSAO)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR);

ALTER TABLE DBSINGULAR.TB_ANOTACAO_FORMULARIO
   ADD CONSTRAINT FK_ANOTFORM_VERANOTFORM FOREIGN KEY (CO_VERSAO_ANOTACAO_ATUAL)
      REFERENCES DBSINGULAR.TB_VERSAO_ANOTACAO_FORMULARIO (CO_VERSAO_ANOTACAO);

ALTER TABLE DBSINGULAR.TB_ANOTACAO_FORMULARIO
   ADD CONSTRAINT FK_ANOTFORM_VERSAOFORM FOREIGN KEY (CO_VERSAO_FORMULARIO)
      REFERENCES DBSINGULAR.TB_VERSAO_FORMULARIO (CO_VERSAO_FORMULARIO);

CREATE UNIQUE INDEX IX_TIPO_FORMULARIO ON DBSINGULAR.TB_TIPO_FORMULARIO (
  SG_TIPO_FORMULARIO ASC
);