-- Scripts de inserção FKs

SET DATABASE SQL SYNTAX MSS TRUE;

ALTER TABLE DBSINGULAR.RL_PERMISSAO_PROCESSO
   ADD CONSTRAINT FK_PERMISSAO_PROCESSO_DEFINICAO_PROCESSO FOREIGN KEY (CO_DEFINICAO_PROCESSO)
      REFERENCES DBSINGULAR.TB_DEFINICAO_PROCESSO (CO_DEFINICAO_PROCESSO)


ALTER TABLE DBSINGULAR.RL_PERMISSAO_TAREFA
   ADD CONSTRAINT FK_PERMISSAO_TAREFA_DEFINICAO_TAREFA FOREIGN KEY (CO_DEFINICAO_TAREFA)
      REFERENCES DBSINGULAR.TB_DEFINICAO_TAREFA (CO_DEFINICAO_TAREFA)


ALTER TABLE DBSINGULAR.TB_DEFINICAO_PROCESSO
   ADD CONSTRAINT FK_DEFINICAO_PROCESSO_CATEGORIA FOREIGN KEY (CO_CATEGORA)
      REFERENCES DBSINGULAR.TB_CATEGORIA (CO_CATEGORIA)


ALTER TABLE DBSINGULAR.TB_DEFINICAO_TAREFA
   ADD CONSTRAINT FK_TB_DEFIN_FK_DEFINI_TB_DEFIN FOREIGN KEY (CO_DEFINICAO_PROCESSO)
      REFERENCES DBSINGULAR.TB_DEFINICAO_PROCESSO (CO_DEFINICAO_PROCESSO)


ALTER TABLE DBSINGULAR.TB_HISTORICO_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_HISTORICO_ALOCACAO_TAREFA_CAD_PESSOA1 FOREIGN KEY (CO_ATOR_ALOCADO)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR)


ALTER TABLE DBSINGULAR.TB_HISTORICO_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_HISTORICO_ALOCACAO_TAREFA_CAD_PESSOA2 FOREIGN KEY (CO_ATOR_ALOCADOR)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR)


ALTER TABLE DBSINGULAR.TB_HISTORICO_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_HISTORICO_ALOCACAO_TAREFA_DMD_TAREFA FOREIGN KEY (CO_INSTANCIA_TAREFA)
      REFERENCES DBSINGULAR.TB_INSTANCIA_TAREFA (CO_INSTANCIA_TAREFA)
         ON DELETE CASCADE


ALTER TABLE DBSINGULAR.TB_HISTORICO_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_HISTORICO_ALOCACAO_TAREFA_DMD_TIPO_HISTORICO_TAREFA FOREIGN KEY (CO_TIPO_HISTORICO_TAREFA)
      REFERENCES DBSINGULAR.TB_TIPO_HISTORICO_TAREFA (CO_TIPO_HISTORICO_TAREFA)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PAPEL
   ADD CONSTRAINT FK_DMD_PAPEL_DEMANDA_CAD_PESSOA FOREIGN KEY (CO_ATOR)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PAPEL
   ADD CONSTRAINT FK_DMD_PAPEL_DEMANDA_CAD_PESSOA1 FOREIGN KEY (CO_ATOR_ALOCADOR)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PAPEL
   ADD CONSTRAINT FK_DMD_PAPEL_DEMANDA_DMD_DEMANDA FOREIGN KEY (CO_INSTANCIA_PROCESSO)
      REFERENCES DBSINGULAR.TB_INSTANCIA_PROCESSO (CO_INSTANCIA_PROCESSO)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PAPEL
   ADD CONSTRAINT FK_DMD_PAPEL_DEMANDA_DMD_PAPEL FOREIGN KEY (CO_PAPEL)
      REFERENCES DBSINGULAR.TB_PAPEL (CO_PAPEL)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PROCESSO
   ADD CONSTRAINT FK_INSTANCIA_PROCESSO_ATOR_CRIADOR FOREIGN KEY (CO_ATOR_CRIADOR)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PROCESSO
   ADD CONSTRAINT FK_DMD_DEMANDA_DMD_TAREFA FOREIGN KEY (CO_INSTANCIA_TAREFA_PAI)
      REFERENCES DBSINGULAR.TB_INSTANCIA_TAREFA (CO_INSTANCIA_TAREFA)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PROCESSO
   ADD CONSTRAINT FK_DMD_DEMANDA_DMD_DEFINICAO FOREIGN KEY (CO_PROCESSO)
      REFERENCES DBSINGULAR.TB_PROCESSO (CO_PROCESSO)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_PROCESSO
   ADD CONSTRAINT FK_TB_INSTA_REFERENCE_TB_TAREF FOREIGN KEY (CO_TAREFA_ATUAL)
      REFERENCES DBSINGULAR.TB_TAREFA (CO_TAREFA)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_TAREFA_CAD_PESSOA1 FOREIGN KEY (CO_ATOR_ALOCADO)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_TAREFA_CAD_PESSOA2 FOREIGN KEY (CO_ATOR_CONCLUSAO)
      REFERENCES DBSINGULAR.TB_ATOR (CO_ATOR)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_TAREFA_DMD_DEMANDA1 FOREIGN KEY (CO_INSTANCIA_PROCESSO)
      REFERENCES DBSINGULAR.TB_INSTANCIA_PROCESSO (CO_INSTANCIA_PROCESSO)
         ON DELETE CASCADE


ALTER TABLE DBSINGULAR.TB_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_DMD_TAREFA_DMD_SITUACAO FOREIGN KEY (CO_TAREFA)
      REFERENCES DBSINGULAR.TB_TAREFA (CO_TAREFA)


ALTER TABLE DBSINGULAR.TB_INSTANCIA_TAREFA
   ADD CONSTRAINT FK_TB_INSTA_FK_INSTAN_TB_TRANS FOREIGN KEY (CO_TRANSICAO_EXECUTADA)
      REFERENCES DBSINGULAR.TB_TRANSICAO (CO_TRANSICAO)


ALTER TABLE DBSINGULAR.TB_PAPEL
   ADD CONSTRAINT FK_PAPEL_DEFINICAO_PROCESSO FOREIGN KEY (CO_DEFINICAO_PROCESSO)
      REFERENCES DBSINGULAR.TB_DEFINICAO_PROCESSO (CO_DEFINICAO_PROCESSO)


ALTER TABLE DBSINGULAR.TB_PROCESSO
   ADD CONSTRAINT FK_TB_PROCE_FK_PROCES_TB_DEFIN FOREIGN KEY (CO_DEFINICAO_PROCESSO)
      REFERENCES DBSINGULAR.TB_DEFINICAO_PROCESSO (CO_DEFINICAO_PROCESSO)


ALTER TABLE DBSINGULAR.TB_TAREFA
   ADD CONSTRAINT FK_TB_TAREF_FK_TAREFA_TB_DEFIN FOREIGN KEY (CO_DEFINICAO_TAREFA)
      REFERENCES DBSINGULAR.TB_DEFINICAO_TAREFA (CO_DEFINICAO_TAREFA)


ALTER TABLE DBSINGULAR.TB_TAREFA
   ADD CONSTRAINT FK_DMD_SITUACAO_DMD_DEFINICAO FOREIGN KEY (CO_PROCESSO)
      REFERENCES DBSINGULAR.TB_PROCESSO (CO_PROCESSO)
         ON DELETE CASCADE


ALTER TABLE DBSINGULAR.TB_TAREFA
   ADD CONSTRAINT FK_DMD_SITUACAO_DMD_TIPO_SITUACAO FOREIGN KEY (CO_TIPO_TAREFA)
      REFERENCES DBSINGULAR.TB_TIPO_TAREFA (CO_TIPO_TAREFA)


ALTER TABLE DBSINGULAR.TB_TRANSICAO
   ADD CONSTRAINT FK_TRANSICAO_TAREFA_DESTINO FOREIGN KEY (CO_TAREFA_DESTINO)
      REFERENCES DBSINGULAR.TB_TAREFA (CO_TAREFA)


ALTER TABLE DBSINGULAR.TB_TRANSICAO
   ADD CONSTRAINT FK_TRANSICAO_TAREFA_ORIGEM FOREIGN KEY (CO_TAREFA_ORIGEM)
      REFERENCES DBSINGULAR.TB_TAREFA (CO_TAREFA)


ALTER TABLE DBSINGULAR.TB_VARIAVEL
   ADD CONSTRAINT FK_DMD_VARIAVEL_DMD_DEMANDA FOREIGN KEY (CO_INSTANCIA_PROCESSO)
      REFERENCES DBSINGULAR.TB_INSTANCIA_PROCESSO (CO_INSTANCIA_PROCESSO)
         ON DELETE CASCADE


ALTER TABLE DBSINGULAR.TB_VARIAVEL
   ADD CONSTRAINT FK_DMD_VARIAVEL_DMD_TIPO_VARIAVEL FOREIGN KEY (CO_TIPO_VARIAVEL)
      REFERENCES DBSINGULAR.TB_TIPO_VARIAVEL (CO_TIPO_VARIAVEL)


ALTER TABLE DBSINGULAR.TB_VARIAVEL_EXECUCAO_TRANSICAO
   ADD CONSTRAINT FK_DMD_HISTORICO_VARIAVEL_DMD_DEMANDA FOREIGN KEY (CO_INSTANCIA_PROCESSO)
      REFERENCES DBSINGULAR.TB_INSTANCIA_PROCESSO (CO_INSTANCIA_PROCESSO)


ALTER TABLE DBSINGULAR.TB_VARIAVEL_EXECUCAO_TRANSICAO
   ADD CONSTRAINT FK_TB_VARIA_FK_HISTOR_TB_TIPO_ FOREIGN KEY (CO_TIPO_VARIAVEL)
      REFERENCES DBSINGULAR.TB_TIPO_VARIAVEL (CO_TIPO_VARIAVEL)


ALTER TABLE DBSINGULAR.TB_VARIAVEL_EXECUCAO_TRANSICAO
   ADD CONSTRAINT FK_TB_VARIA_FK_HISTOR_TB_VARIA FOREIGN KEY (CO_VARIAVEL_INSTANCIA_PROCESSO)
      REFERENCES DBSINGULAR.TB_VARIAVEL (CO_VARIAVEL)


ALTER TABLE DBSINGULAR.TB_VARIAVEL_EXECUCAO_TRANSICAO
   ADD CONSTRAINT PK_HISTORICO_VARIAVEL_INSTANCIA_TAREFA_DESTINO FOREIGN KEY (CO_INSTANCIA_TAREFA_DESTINO)
      REFERENCES DBSINGULAR.TB_INSTANCIA_TAREFA (CO_INSTANCIA_TAREFA)


ALTER TABLE DBSINGULAR.TB_VARIAVEL_EXECUCAO_TRANSICAO
   ADD CONSTRAINT PK_HISTORICO_VARIAVEL_INSTANCIA_TAREFA_ORIGEM FOREIGN KEY (CO_INSTANCIA_TAREFA_ORIGEM)
      REFERENCES DBSINGULAR.TB_INSTANCIA_TAREFA (CO_INSTANCIA_TAREFA)

/*==============================================================*/
/* Index: IX_INSTANCIA_PROCESSO                                 */
/*==============================================================*/
CREATE INDEX IX_INSTANCIA_PROCESSO ON DBSINGULAR.TB_INSTANCIA_PROCESSO (
CO_PROCESSO ASC,
DT_INICIO ASC
)

	  
/*==============================================================*/
/* Index: IX_HISTORICO_INSTANCIA_TAREFA                         */
/*==============================================================*/
CREATE INDEX IX_HISTORICO_INSTANCIA_TAREFA ON DBSINGULAR.TB_HISTORICO_INSTANCIA_TAREFA (
CO_INSTANCIA_TAREFA ASC,
DT_INICIO_ALOCACAO ASC
)


/*==============================================================*/
/* Index: IX_INSTANCIA_TAREFA                                   */
/*==============================================================*/
CREATE INDEX IX_INSTANCIA_TAREFA ON DBSINGULAR.TB_INSTANCIA_TAREFA (
CO_INSTANCIA_PROCESSO ASC,
DT_INICIO ASC
)

/*==============================================================*/
/* Index: IX_PROCESSO                                           */
/*==============================================================*/
CREATE INDEX IX_PROCESSO ON DBSINGULAR.TB_PROCESSO (
CO_DEFINICAO_PROCESSO ASC,
DT_VERSAO ASC
)
