-- java -cp ~/.m2/repository/org/hsqldb/hsqldb/2.3.2/hsqldb-2.3.2.jar org.hsqldb.util.DatabaseManager

CREATE SEQUENCE DBSINGULAR.SQ_CO_CATEGORIA  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_DEFINICAO_PROCESSO  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_DEFINICAO_TAREFA    START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_HISTORICO_ALOCACAO     START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_INSTANCIA_PAPEL     START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_INSTANCIA_PROCESSO    START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_INSTANCIA_TAREFA     START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_PAPEL               START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_PROCESSO            START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_TAREFA            START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_TIPO_HISTORICO_TAREFA  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_TIPO_VARIAVEL  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_TRANSICAO       START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_VARIAVEL            START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_VARIAVEL_EXECUCAO_TRANSICAO  START WITH 1 INCREMENT BY 1;


ALTER TABLE DBSINGULAR.TB_CATEGORIA ALTER COLUMN 	CO_CATEGORIA DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_DEFINICAO_PROCESSO ALTER COLUMN 	CO_DEFINICAO_PROCESSO DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_DEFINICAO_TAREFA ALTER COLUMN 	CO_DEFINICAO_TAREFA   DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_HISTORICO_INSTANCIA_TAREFA ALTER COLUMN 	CO_HISTORICO_ALOCACAO    DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_INSTANCIA_PAPEL ALTER COLUMN 	CO_INSTANCIA_PAPEL    DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_INSTANCIA_PROCESSO ALTER COLUMN 	CO_INSTANCIA_PROCESSO   DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_INSTANCIA_TAREFA ALTER COLUMN 	CO_INSTANCIA_TAREFA    DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_PAPEL ALTER COLUMN 	CO_PAPEL              DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_PROCESSO ALTER COLUMN 	CO_PROCESSO           DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_TAREFA ALTER COLUMN 	CO_TAREFA           DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_TIPO_HISTORICO_TAREFA ALTER COLUMN 	CO_TIPO_HISTORICO_TAREFA DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_TIPO_TAREFA ALTER COLUMN 	CO_TIPO_TAREFA DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_TIPO_VARIAVEL ALTER COLUMN CO_TIPO_VARIAVEL DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_TRANSICAO ALTER COLUMN 		CO_TRANSICAO      DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_VARIAVEL ALTER COLUMN 	CO_VARIAVEL           DROP GENERATED;
ALTER TABLE DBSINGULAR.TB_VARIAVEL_EXECUCAO_TRANSICAO ALTER COLUMN CO_VARIAVEL_EXECUCAO_TRANSICAO DROP GENERATED;


--
-- ALTER TABLE DBSINGULAR.TB_CATEGORIA					ADD CONSTRAINT 			PK_CATEGORIA			PRIMARY KEY (	CO_CATEGORIA);
-- ALTER TABLE DBSINGULAR.TB_DEFINICAO_PROCESSO					ADD CONSTRAINT 			PK_DEFINICAO_PROCESSO			PRIMARY KEY (	CO_DEFINICAO_PROCESSO);
-- ALTER TABLE DBSINGULAR.TB_DEFINICAO_TAREFA					ADD CONSTRAINT 			PK_DEFINICAO_TAREFA  			PRIMARY KEY (	CO_DEFINICAO_TAREFA);
-- ALTER TABLE DBSINGULAR.TB_HISTORICO_INSTANCIA_TAREFA 					ADD CONSTRAINT 			PK_HISTORICO_ALOCACAO   			PRIMARY KEY (	CO_HISTORICO_ALOCACAO);
-- ALTER TABLE DBSINGULAR.TB_INSTANCIA_PAPEL					ADD CONSTRAINT 			PK_INSTANCIA_PAPEL   			PRIMARY KEY (	CO_INSTANCIA_PAPEL);
-- ALTER TABLE DBSINGULAR.TB_INSTANCIA_PROCESSO					ADD CONSTRAINT 			PK_INSTANCIA_PROCESSO  			PRIMARY KEY (	CO_INSTANCIA_PROCESSO);
-- ALTER TABLE DBSINGULAR.TB_INSTANCIA_TAREFA					ADD CONSTRAINT 			PK_INSTANCIA_TAREFA   			PRIMARY KEY (	CO_INSTANCIA_TAREFA);
-- ALTER TABLE DBSINGULAR.TB_PAPEL					ADD CONSTRAINT 			PK_PAPEL             			PRIMARY KEY (	CO_PAPEL);
-- ALTER TABLE DBSINGULAR.TB_PROCESSO					ADD CONSTRAINT 			PK_PROCESSO          			PRIMARY KEY (	CO_PROCESSO);
-- ALTER TABLE DBSINGULAR.TB_TAREFA					ADD CONSTRAINT 			PK_TAREFA          			PRIMARY KEY (	CO_TAREFA);
-- ALTER TABLE DBSINGULAR.TB_TIPO_HISTORICO_TAREFA					ADD CONSTRAINT 			PK_TIPO_HISTORICO_TAREFA			PRIMARY KEY (	CO_TIPO_HISTORICO_TAREFA);
-- ALTER TABLE DBSINGULAR.TB_TIPO_TAREFA					ADD CONSTRAINT 			PK_TIPO_TAREFA			PRIMARY KEY (	CO_TIPO_TAREFA);
-- ALTER TABLE DBSINGULAR.TB_TIPO_VARIAVEL					ADD CONSTRAINT 			PK_TIPO_VARIAVEL			PRIMARY KEY (	CO_TIPO_VARIAVEL);
-- ALTER TABLE DBSINGULAR.TB_TRANSICAO					ADD CONSTRAINT 			PK_TRANSICAO     			PRIMARY KEY (	CO_TRANSICAO);
-- ALTER TABLE DBSINGULAR.TB_VARIAVEL					ADD CONSTRAINT 			PK_VARIAVEL          			PRIMARY KEY (	CO_VARIAVEL);
-- ALTER TABLE DBSINGULAR.TB_VARIAVEL_EXECUCAO_TRANSICAO					ADD CONSTRAINT 			PK_VARIAVEL_EXECUCAO_TRANSICAO			PRIMARY KEY (	CO_VARIAVEL_EXECUCAO_TRANSICAO);
